version: '3.4'

services:
  tinyplants:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ConnectionStrings__DefaultConnection=Server=db;Database=StoreDbContext;User=sa;Password=Kim12341234!
    ports:
      - "80"
      - "443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Kim12341234!"
    ports:
      - 1433:1433